apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartsmith-app
spec:
  template:
    spec:
      containers:
        - name: chartsmith-app
          command: ["npm"]
          args: ["run", "dev"]
          workingDir: /app
          ports:
            - containerPort: 3000
              protocol: TCP
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: env-file
              mountPath: /app/.env.local
              subPath: .env.local
      volumes:
        - name: env-file
          secret:
            secretName: chartsmith-app
