apiVersion: v1
kind: Secret
metadata:
  name: chartsmith-app
type: Opaque
stringData:
  .env.local: |-
    NEXT_PUBLIC_GOOGLE_CLIENT_ID=730758876435-8v7frmnqtt7k7v65edpc6u3hso9olqbe.apps.googleusercontent.com
    NEXT_PUBLIC_GOOGLE_REDIRECT_URI=https://chartsmith-app-$OKTETO_NAMESPACE.okteto.repldev.com/auth/google
    GOOGLE_CLIENT_SECRET=$CHARTSMITH_GOOGLE_CLIENT_SECRET
    DB_URI=postgresql://chartsmith:password@chartsmith-postgres/chartsmith?connect_timeout=10&application_name=chartsmith&sslmode=disable
    HMAC_SECRET=not-secure
    CENTRIFUGO_TOKEN_HMAC_SECRET=change.me
    NEXT_PUBLIC_CENTRIFUGO_ADDRESS=wss://chartsmith-push-$OKTETO_NAMESPACE.okteto.repldev.com/connection/websocket
    TOKEN_ENCRYPTION=$CHARTSMITH_TOKEN_ENCRYPTION
    NEXT_PUBLIC_REPLICATED_REDIRECT_URI=https://vendor-web-marccampbell.okteto.repldev.com/chartsmith-login?redirect_uri=https://chartsmith-app-marccampbell.okteto.repldev.com/auth/replicated
