apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartsmith-worker
spec:
  template:
    spec:
      containers:
        - name: chartsmith-worker
          command:
            - /go/src/github.com/replicatedhq/chartsmith/bin/chartsmith-worker
          args:
            - "run"
            - "--pg-uri=$(PG_URI)"
            - "--centrifugo-address=http://chartsmith-centrifugo:8000/api"
            - "--centrifugo-api-key=api_key"
          workingDir: /go/src/github.com/replicatedhq/chartsmith
          env:
            - name: PG_URI
              valueFrom:
                secretKeyRef:
                  name: chartsmith-postgres
                  key: uri
            - name: ANTHROPIC_API_KEY
              value: $CHARTSMITH_ANTHROPIC_API_KEY
            - name: VOYAGE_API_KEY
              value: $VOYAGE_API_KEY
          envFrom:
            - secretRef:
                name: chartsmith-postgres
          readinessProbe: ~
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
      initContainers:
      - image: chartsmith-worker
        name: bootstrap
        command:
          - /go/src/github.com/replicatedhq/chartsmith/bin/chartsmith-worker
        args:
          - "bootstrap"
          - "--pg-uri=$(PG_URI)"
          - "--chart-dir=//go/src/github.com/replicatedhq/chartsmith/bootstrap-chart"
        env:
          - name: PG_URI
            valueFrom:
              secretKeyRef:
                name: chartsmith-postgres
                key: uri
          - name: ANTHROPIC_API_KEY
            value: $CHARTSMITH_ANTHROPIC_API_KEY
          - name: VOYAGE_API_KEY
            value: $VOYAGE_API_KEY
        envFrom:
          - secretRef:
              name: chartsmith-postgres
        readinessProbe: ~
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
