apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartsmith-app
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: chartsmith-app
  template:
    metadata:
      labels:
        app: chartsmith-app
    spec:
      containers:
        - name: chartsmith-app
          image: chartsmith-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3000"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
