FROM golang:1.23

WORKDIR /go/src/github.com/replicatedhq/chartsmith

# Download and install Helm 3.17.0
RUN curl -LO https://get.helm.sh/helm-v3.17.0-linux-amd64.tar.gz && \
    tar -xzf helm-v3.17.0-linux-amd64.tar.gz && \
    mv linux-amd64/helm /usr/local/bin/helm-v3.17.0 && \
    rm -rf linux-amd64 helm-v3.17.0-linux-amd64.tar.gz

# Symlink helm to helm-v3.17.0
RUN ln -s /usr/local/bin/helm-v3.17.0 /usr/local/bin/helm

# Copy the entire project first
COPY . .

# Now run go mod download after we have all the files
RUN go mod download -x

RUN make build

CMD ["/go/src/github.com/replicatedhq/chartsmith/bin/chartsmith-worker"]
