apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartsmith-worker
spec:
  template:
    spec:
      containers:
        - name: chartsmith-worker
          readinessProbe: ~
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
          env:
            - name: USE_EC2_PARAMETERS
              value: "true"
            - name: AWS_REGION
              value: us-east-1
