{{- if .Values.centrifugo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chartsmith.fullname" . }}-centrifugo
  labels:
    {{- include "chartsmith.labels" (dict "Chart" .Chart "Values" (merge .Values (dict "component" "centrifugo")) "Release" .Release "Files" .Files) | nindent 4 }}
    app.kubernetes.io/component: centrifugo
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "chartsmith.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: centrifugo
{{- end }}
