apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chartsmith.fullname" . }}-app
  labels:
    {{- include "chartsmith.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chartsmith.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        {{- include "chartsmith.selectorLabels" . | nindent 8 }}
        {{- include "chartsmith.labels" . | nindent 8 }}
        app.kubernetes.io/component: app
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if and .Values.global .Values.global.replicated .Values.global.replicated.dockerconfigjson }}
      imagePullSecrets:
        - name: chartsmith-image-pull-secret
      {{- else if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chartsmith.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.app.registry }}/{{ .Values.images.app.repository }}:{{ .Values.images.app.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.app.pullPolicy }}
          env:
          - name: CENTRIFUGO_TOKEN_HMAC_SECRET
            valueFrom:
              secretKeyRef:
                key: CENTRIFUGO_TOKEN_HMAC_SECRET
                name: {{ include "chartsmith.centrifugoTokenHmacSecret" . }}
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: GOOGLE_CLIENT_SECRET
                name: {{ include "chartsmith.googleClientSecret" . }}
          - name: HMAC_SECRET
            valueFrom:
              secretKeyRef:
                key: HMAC_SECRET
                name: {{ include "chartsmith.hmacSecret" . }}
          - name: CHARTSMITH_PG_URI
            {{- include "chartsmith.pgUri" . | trim | nindent 12 }}
          - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
                name: chartsmith-configs
          - name: NEXT_PUBLIC_CENTRIFUGO_ADDRESS
            valueFrom:
              configMapKeyRef:
                key: NEXT_PUBLIC_CENTRIFUGO_ADDRESS
                name: chartsmith-configs
          - name: NEXT_PUBLIC_GOOGLE_REDIRECT_URI
            valueFrom:
              configMapKeyRef:
                key: NEXT_PUBLIC_GOOGLE_REDIRECT_URI
                name: chartsmith-configs
          - name: ANTHROPIC_API_KEY
            valueFrom:
              secretKeyRef:
                key: ANTHROPIC_API_KEY
                name: {{ include "chartsmith.anthropicApiKey" . }}
          - name: NEXT_PUBLIC_API_ENDPOINT
            valueFrom:
              configMapKeyRef:
                key: NEXT_PUBLIC_API_ENDPOINT
                name: chartsmith-configs
          - name: NEXT_PUBLIC_ENABLE_TEST_AUTH
            valueFrom:
              configMapKeyRef:
                key: NEXT_PUBLIC_ENABLE_TEST_AUTH
                name: chartsmith-configs
          - name: NEXT_PUBLIC_REPLICATED_REDIRECT_URI
            valueFrom:
              configMapKeyRef:
                key: NEXT_PUBLIC_REPLICATED_REDIRECT_URI
                name: chartsmith-configs
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
