# templates/image-pull-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: chartsmith-image-pull-secret
  labels:
    {{- include "chartsmith.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.replicated.dockerconfigjson | quote }}
