apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartsmith-migrations
  labels:
    app: chartsmith-migrations
spec:
  selector:
    matchLabels:
      app: chartsmith-migrations
  template:
    metadata:
      labels:
        app: chartsmith-migrations
    spec:
      volumes:
        - name: chartsmith-migrations
          emptyDir:
            medium: Memory
      containers:
      - image: migrations
        name: pause
        command:
          - sleep
          - infinity
        volumeMounts:
          - name: chartsmith-migrations
            mountPath: /migrations
        env:
          - name: SCHEMAHERO_DRIVER
            value: postgres
          - name: SCHEMAHERO_SPEC_FILE
            value: /go/src/github.com/replicatedhq/chartsmith/db/schema/tables
          - name: SCHEMAHERO_OUT
            value: /migrations/plan.yaml
          - name: SCHEMAHERO_DDL
            value: /migrations/plan.yaml
          - name: SCHEMAHERO_URI
            value: postgresql://chartsmith:password@chartsmith-postgres/chartsmith?connect_timeout=10&application_name=chartsmith&sslmode=disable
      initContainers:
      - image: pgvector/pgvector:pg16
        name: pgveector-init
        command:
          - sh
          - -c
          - |
            psql "postgresql://chartsmith:password@chartsmith-postgres/chartsmith?connect_timeout=10&application_name=chartsmith&sslmode=disable" -c "CREATE EXTENSION IF NOT EXISTS vector"
      - image: migrations
        name: migrations-plan
        volumeMounts:
          - name:  chartsmith-migrations
            mountPath: /migrations
        args: ["plan"]
        env:
          - name: SCHEMAHERO_DRIVER
            value: postgres
          - name: SCHEMAHERO_SPEC_FILE
            value: /go/src/github.com/replicatedhq/chartsmith/db/schema/tables
          - name: SCHEMAHERO_OUT
            value: /migrations/plan.yaml
          - name: SCHEMAHERO_URI
            value: postgresql://chartsmith:password@chartsmith-postgres/chartsmith?connect_timeout=10&application_name=chartsmith&sslmode=disable
          - name: SCHEMAHERO_SEED_DATA
            value: "true"
      - image: migrations
        name: migrations-apply
        volumeMounts:
          - name:  chartsmith-migrations
            mountPath: /migrations
        args: ["apply"]
        env:
          - name: SCHEMAHERO_DRIVER
            value: postgres
          - name: SCHEMAHERO_DDL
            value: /migrations/plan.yaml
          - name: SCHEMAHERO_URI
            value: postgresql://chartsmith:password@chartsmith-postgres/chartsmith?connect_timeout=10&application_name=chartsmith&sslmode=disable
