apiVersion: v1
kind: ConfigMap
metadata:
  name: chartsmith-centrifugo-config
data:
  config.json: |-
    {
      "token_hmac_secret_key": "change.me",
      "admin_password": "password",
      "admin_secret": "secret",
      "api_key": "api_key",
      "allowed_origins": ["*"],
      "allow_user_limited_channels": true
    }
---
apiVersion: v1
kind: Service
metadata:
  name: chartsmith-centrifugo
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: external
      protocol: TCP
      name: external
  selector:
    app.kubernetes.io/name: chartsmith-centrifugo
    app.kubernetes.io/instance: chartsmith-centrifugo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chartsmith-push
  annotations:
    dev.okteto.com/generate-host: "true"
    dev.okteto.com/endpoints: wss://chartsmith-push-${OKTETO_NAMESPACE}.${OKTETO_DOMAIN}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chartsmith-centrifugo
                port:
                  number: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartsmith-centrifugo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chartsmith-centrifugo
      app.kubernetes.io/instance: chartsmith-centrifugo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chartsmith-centrifugo
        app.kubernetes.io/instance: chartsmith-centrifugo
    spec:
      terminationGracePeriodSeconds: 30
      volumes:
        - name: chartsmith-centrifugo-config
          configMap:
            name: chartsmith-centrifugo-config
      enableServiceLinks: false
      containers:
        - name: centrifugo
          image: docker.io/centrifugo/centrifugo:v5.4.5
          command:
            - centrifugo
          args:
            - -c
            - /centrifugo/config.json
          volumeMounts:
            - name: "chartsmith-centrifugo-config"
              mountPath: "/centrifugo"
              readOnly: true
          ports:
            - name: external
              containerPort: 8000
