FROM schemahero/schemahero:0.17.13 as schemahero

FROM ubuntu:22.04

COPY --from=schemahero /schemahero /schemahero
ENTRYPOINT ["/schemahero"]

WORKDIR /go/src/github.com/replicatedhq/chartsmith/db/schema/tables

RUN apt-get update && \
    apt-get install -y build-essential && \
    rm -rf /var/lib/apt/lists/*

COPY ./db/schema/tables .
