apiVersion: kots.io/v1beta1
kind: Terraform
metadata:
  name: azure-infra
spec:
  # filename references a .tgz file containing Terraform modules
  filename: terraform-module-v1.0.0.tgz
  
  # minTerraformVersion specifies the minimum Terraform version required
  minTerraformVersion: "1.5.0"
  
  # docs provides documentation for various user-defined steps
  docs:
    prerequisites: |
      Before installing this Terraform configuration, ensure you have:
      - Azure CLI (az) configured with credentials
      - Terraform installed (>= 1.5.0)
      - Sufficient Azure permissions:
        - Network Contributor (VNet, Subnets, NSG)
        - Azure Kubernetes Service Contributor (AKS cluster)
        - SQL DB Contributor (Azure Database for PostgreSQL)
        - Key Vault Administrator (Key Vault for secrets)
        - Managed Identity Operator (Service identities)
      - Azure subscription with sufficient quotas:
        - Virtual Networks: 1 additional (if creating new VNet)
        - Azure Database for PostgreSQL instances: 1 additional
        - AKS clusters: 1 additional
        - Standard SKU Load Balancers: 1 additional
    install: |
      This step initializes and applies the Terraform configuration.
      
      1. Choose Your Deployment Scenario:
         - Minimal - Create everything from scratch (recommended for new deployments)
         - Existing VNet - Use your existing Virtual Network infrastructure
         - Existing Cluster - Use your existing AKS cluster
      
      2. Create Infrastructure:
         ```bash
         cd examples/minimal  # or your chosen example
         cp terraform.tfvars.example terraform.tfvars
         # Edit terraform.tfvars with your values
         terraform init
         terraform plan
         terraform apply
         ```
      
      3. Basic Configuration:
         ```hcl
         # Environment identification
         environment_name = "production"
         azure_region = "eastus"
         resource_group_name = "chartsmith-rg"
         
         # Infrastructure choices
         create_vnet = true         # Create new Virtual Network
         create_database = true     # Create Azure Database for PostgreSQL
         ```
