version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: chartsmith-e2e-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chartsmith
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres_e2e_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: "no"
    # Disable IPv6 binding
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  centrifugo:
    image: centrifugo/centrifugo:v5
    container_name: chartsmith-e2e-centrifugo
    ports:
      - "127.0.0.1:8001:8001"
    command: centrifugo --config /centrifugo/config.json
    volumes:
      - ./centrifugo:/centrifugo
    restart: "no"
    # Disable IPv6 binding
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

volumes:
  postgres_e2e_data:
    name: chartsmith-e2e-postgres-data
