version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chartsmith
    ports:
      - "5433:5432"
    volumes:
      - postgres_e2e_data:/var/lib/postgresql/data

  centrifugo:
    image: centrifugo/centrifugo:v5
    ports:
      - "8001:8000"
    command: centrifugo --config /centrifugo/config.json
    volumes:
      - ./centrifugo:/centrifugo

volumes:
  postgres_e2e_data:
