/* Auto generated file. Do not edit by hand. This file was generated by SchemaHero. */

create table "bootstrap_file" ("file_path" text not null, "content" text not null, "name" text not null, primary key ("file_path"));
create table "bootstrap_gvk" ("id" text not null, "gvk" text not null, "file_path" text not null, "content" text not null, "summary" text, "embeddings" vector (1024), primary key ("id"));
create table "bootstrap_meta" ("key" text not null, "value" text not null, primary key ("key"));
create table "chartsmith_user" ("id" text not null, "email" text not null, "name" text not null, "image_url" text not null, "created_at" timestamp not null, "last_login_at" timestamp, "last_active_at" timestamp, "replicated_token" text, primary key ("id"));
create table "notification_processing" ("notification_channel" text not null, "notification_id" text not null, "claimed_at" timestamp not null, "claimed_by" text not null, "processed_at" timestamp, "error" text, primary key ("notification_channel", "notification_id"));
create table "session" ("id" text not null, "user_id" text not null, "expires_at" timestamp not null, primary key ("id"));
create table "slack_notification" ("id" text not null, "created_at" timestamp not null, "user_id" text, "workspace_id" text, "notification_type" text not null, "additional_data" text, primary key ("id"));
create table "workspace_chat" ("id" text not null, "workspace_id" text not null, "is_initial_message" boolean not null, "created_at" timestamp not null, "sent_by" text not null, "prompt" text not null, "response" text, "is_complete" boolean not null, "files_sent" text[], "is_applied" boolean not null default 'false', "is_applying" boolean not null default 'false', "is_ignored" boolean not null default 'false', primary key ("id"));
create table "workspace_file" ("workspace_id" text not null, "file_path" text not null, "revision_number" integer not null, "created_at" timestamp not null, "last_updated_at" timestamp, "content" text not null, "name" text not null, primary key ("workspace_id", "file_path", "revision_number"));
create table "workspace_gvk" ("id" text not null, "workspace_id" text not null, "gvk" text not null, "revision_number" integer not null, "file_path" text not null, "created_at" timestamp not null, "content" text not null, "summary" text, "embeddings" vector (1024), primary key ("id"));
create table "workspace_revision" ("workspace_id" text not null, "revision_number" integer not null, "created_at" timestamp not null, "chat_message_id" text, "created_by_user_id" text not null, "created_type" text not null, "is_complete" boolean not null, primary key ("workspace_id", "revision_number"));
create table "workspace" ("id" text not null, "created_at" timestamp not null, "last_updated_at" timestamp, "name" text not null, "created_by_user_id" text not null, "created_type" text not null, "current_revision_number" integer not null, primary key ("id"));

INSERT INTO bootstrap_meta (key, value) VALUES ('current_directory_hash', 'fea06d3028c221624ca2c90e5688a6d0c2112b6800482712acca44664e0f5505');
